[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#000000"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#000000"
font = "sans serif"
